//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundTransfer
    {
        public int TransferID { get; set; }
        public string FromAccountID { get; set; }
        public string ToAccountID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransferDate { get; set; }
        public string FromCustomerID { get; set; }
        public string ToCustomerID { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual SavingsAccount SavingsAccount { get; set; }
        public virtual SavingsAccount SavingsAccount1 { get; set; }
    }
}
