//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanAccount()
        {
            this.LoanTransactions = new HashSet<LoanTransaction>();
        }
    
        public string Ln_accountid { get; set; }
        public string Customer { get; set; }
        public Nullable<decimal> loan_amount { get; set; }
        public System.DateTime Start_date { get; set; }
        public int Tenure { get; set; }
        public decimal Ln_roi { get; set; }
        public Nullable<decimal> Emi { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Customer Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanTransaction> LoanTransactions { get; set; }
    }
}
