//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanTransaction
    {
        public int Transactionno { get; set; }
        public string Ln_accountid { get; set; }
        public Nullable<System.DateTime> Emidate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Outstanding { get; set; }
        public string PaymentType { get; set; }
        public string PaidBy { get; set; }
    
        public virtual LoanAccount LoanAccount { get; set; }
    }
}
