//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingsTransaction
    {
        public int Transactionid { get; set; }
        public string SBAccountID { get; set; }
        public Nullable<System.DateTime> Transationdate { get; set; }
        public string Transactiontype { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual SavingsAccount SavingsAccount { get; set; }
    }
}
